spring.application.name=snakegame
spring.datasource.url=jdbc:postgresql://localhost:5432/snakedb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
game.snake.board.rows=20
game.snake.board.columns=20
game.snake.loop.rate=50
spring.devtools.restart.enabled=false
spring.task.scheduling.pool.size=4
